capstone/LandingPage/urls.py
from django.urls import path

from . import views

app_name = 'LandingPage'
urlpatterns = [
	path('', views.index, name='index'),
	path('students/', views.StudentListView, name='all_students'),
	path('<int:student_id_in>/student', views.StudentSingleView, name='single_student'),
	path('faculty/', views.FacultyListView, name='all_faculty'),
	path('<int:faculty_id_in>/faculty', views.FacultySingleView, name='single_faculty'),
]

capstone/accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.signup, name = "signup"),
    url(r'^login/$', views.login_view, name = "login"),
    url(r'^logout/$', views.logout_view, name = "logout")
]

capstone/capstone/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('courses/', include('coursesDB.urls', namespace = 'courses')),
    path('opath/', include("opath.urls")),
    url(r'^accounts/', include('accounts.urls')),
  	path('LandingPage/', include('LandingPage.urls')),
    path('course_search/', include('course_search.urls', namespace = 'course_search')),
    path('profile', include('user_profile.urls')),
  	path('', include('LandingPage.urls')),
]

capstone/opath/urls.py
from django.urls import path
from . import views
from django.contrib import admin


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name = 'opath'),
]

capstone/user_profile/urls.py
from django.conf.urls import url
from . import views

app_name = 'user_profile'

urlpatterns = [
    # url(r'^profile/(?P<username>[a-zA-Z0-9]+)$', views.get_profile, name = "profile"),
    url(r'^/$', views.get_profile, name="profile"),
    url(r'edit/$', views.edit_profile, name="edit_profile")
]

capstone/templates/base_layout.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> Capstone - Final Project </title>
  </head>

<link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css"
      integrity="sha384-nn4HPE8lTHyVtfCBi5yW9d20FjT8BJwUXyWZT9InLYax14RDjBj46LmSztkmNP9w"
      crossorigin="anonymous">
<link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/grids-responsive-min.css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
  <body>
    <!-- <h2> Capstone - Course Search </h2> -->

      </div>
      <!-- navbar will go here -->
      {% block navbar %}

      <div class="pure-menu pure-menu-horizontal">
          <ul class="pure-menu-list">
              <li class="pure-menu-item pure-menu-selected"><a href="/" class="pure-menu-link">Home</a></li>
              <li class="pure-menu-item pure-menu-selected"><a href="{% url 'LandingPage:all_students' %}" class="pure-menu-link">Student List</a></li>
              <li class="pure-menu-item pure-menu-selected"><a href="{% url 'LandingPage:all_faculty' %}" class="pure-menu-link">Faculty List </a></li>
              <li class="pure-menu-item pure-menu-selected"><a href="/courses/all" class="pure-menu-link">Course List </a></li>
              <li class="pure-menu-item pure-menu-selected"><a href='/opath' class="pure-menu-link"> Optimal Class Path </a></li>
              <li class="pure-menu-item pure-menu-has-children pure-menu-allow-hover">
                  <a href="{% url 'user_profile:profile' %}" id="menuLink1" class="pure-menu-link">Your Profile</a>
                  <ul class="pure-menu-children">
                      <li class="pure-menu-item">  <a href="{% url 'user_profile:edit_profile' %}" class="pure-menu-link">Edit</a></li>
                        {% if user.is_authenticated %}
                      <!-- <li class="pure-menu-item"><a href="#" class="pure-menu-link">Logout</a></li> -->
                      <form class="logout-button" action="{% url 'accounts:logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit"> Logout </button>
                      </form>
                        {% endif %}
                  </ul>
              </li>
          </ul>
      </div>

      <hr>
      {% endblock %}

        {% block login %}
          <!-- block login -->
        {% endblock %}

      <!-- main content for each page will go here -->

      <br>
      <div>
      <!-- <p> block "content" begins after the line </p> -->
      <hr>

      {% block content %}
      {% endblock %}
      <hr>
    </div>

  </body>
</html>