capstone/LandingPage/urls.py
from django.urls import path

from . import views

app_name = 'LandingPage'
urlpatterns = [
	path('', views.index, name='index'),
	path('students/', views.StudentListView, name='all_students'),
	path('<int:student_id_in>/student', views.StudentSingleView, name='single_student'),
	path('faculty/', views.FacultyListView, name='all_faculty'),
	path('<int:faculty_id_in>/faculty', views.FacultySingleView, name='single_faculty'),
]

capstone/accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.signup, name = "signup"),
    url(r'^login/$', views.login_view, name = "login"),
    url(r'^logout/$', views.logout_view, name = "logout")
]

capstone/capstone/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('courses/', include('coursesDB.urls', namespace = 'courses')),
    path('opath/', include("opath.urls")),
    url(r'^accounts/', include('accounts.urls')),
  	path('LandingPage/', include('LandingPage.urls')),
    path('course_search/', include('course_search.urls', namespace = 'course_search')),
    path('profile', include('user_profile.urls')),
  	path('', include('LandingPage.urls')),
]

capstone/opath/urls.py
from django.urls import path
from . import views
from django.contrib import admin


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name = 'opath'),
]

capstone/user_profile/urls.py
from django.conf.urls import url
from . import views

app_name = 'user_profile'

urlpatterns = [
    # url(r'^profile/(?P<username>[a-zA-Z0-9]+)$', views.get_profile, name = "profile"),
    url(r'^/$', views.get_profile, name="profile"),
    url(r'edit/$', views.edit_profile, name="edit_profile")
]

capstone/LandingPage/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.contrib.auth.decorators import login_required
# Create your views here.

from accounts.models import Faculty, Student

def index(request):
	return render(request, 'LandingPage/index.html')

@login_required(login_url="/accounts/login/")
def StudentSingleView(request, student_id_in):
	try:
		student = Student.objects.get(student_id=student_id_in)
	except:
		return render(request, 'LandingPage/missing_student.html')
	return render(request, 'LandingPage/single_student.html', {'student': student})

@login_required(login_url="/accounts/login/")
def FacultySingleView(request, faculty_id_in):
	try:
		faculty = Faculty.objects.get(faculty_id=faculty_id_in)
	except:
		return render(request, 'LandingPage/missing_faculty.html')
	return render(request, 'LandingPage/single_faculty.html', {'faculty': faculty})

@login_required(login_url="/accounts/login/")
def FacultyListView(request, ):
    faculty_list = []
    query = request.GET.get('q')
    if query:
        try:
            faculty_objects = Faculty.objects.filter(faculty_name_first__contains = query)
            for faculty_object in faculty_objects:
                faculty_list.append(faculty_object)
            faculty_objects = Faculty.objects.filter(faculty_name_last__contains = query)
            for faculty_object in faculty_objects:
                if faculty_object not in faculty_list:
                    faculty_list.append(faculty_object)
        except:
            faculty_list = []
    else:
        faculty_objects = Faculty.objects.all()
        for faculty_object in faculty_objects:
            faculty_list.append(faculty_object)
    return render(request, 'LandingPage/faculty_list.html', {'faculty_list': faculty_list})

@login_required(login_url="/accounts/login/")
def StudentListView(request, ):
    student_list = []
    query = request.GET.get('q')
    if query:
        try:
            student_objects = Student.objects.filter(student_name_first__contains = query)
            for student_object in student_objects:
                student_list.append(student_object)
            student_objects = Student.objects.filter(student_name_last__contains = query)
            for student_object in student_objects:
                if student_object not in student_list:
                    student_list.append(student_object)
        except:
            student_list = []
    else:
        student_objects = Student.objects.all()
        for student_object in student_objects:
            student_list.append(student_object)
    return render(request, 'LandingPage/student_list.html', {'student_list': student_list})

capstone/LandingPage/templates/LandingPage/faculty_list.html
{% extends 'base_layout.html' %}

{% block content %}

<h2> Faculty </h2>

<form method = "GET" action = "{% url 'LandingPage:all_faculty'%}">
    <input name="q" value = "{{request.GET.q}}" placeholder = "search..">
    <button class="btn btn-success" type="submit">
	    Search
	</button>
</form>

{% if faculty_list %}
<ul>
    {% for faculty in faculty_list %}
    <li>
        <a href="{% url 'LandingPage:single_faculty' faculty.faculty_id %}">{{ faculty.faculty_name_last }}</a>
    </li>
    {% endfor %}
</ul>
{% else %}
<p>
    No Faculty Available
</p>
{% endif %}
{% endblock %}

capstone/LandingPage/templates/LandingPage/index.html
{% extends 'base_layout.html' %}

{% block content %}

{% if not user.is_authenticated %}
  <h3> Welcome to Home </h3>
  <p> If you have an account, <a href="{% url 'accounts:login'%}"> Login </a>, otherwise <a href="{% url 'accounts:signup'%}"> Sign Up </a>. </p>
{% endif %}



<!-- <a href="{% url 'LandingPage:all_faculty' %}">Faculty List</a> -->
<!-- <a href="{% url 'LandingPage:all_students' %}">Student List</a> -->
<!-- <a href="{% url 'user_profile:profile' %}">Profile</a> -->

<!-- <h1> Optimal Path</h1> -->
<!-- <a href='/opath'> Optimal Path</a> -->
{% endblock %}

capstone/LandingPage/templates/LandingPage/missing_faculty.html
{% extends 'base_layout.html' %}

{% block content %}

This faculty member does not exist.

{% endblock %}

capstone/LandingPage/templates/LandingPage/missing_student.html
{% extends 'base_layout.html' %}

{% block content %}

This student does not exist.

{% endblock %}

capstone/LandingPage/templates/LandingPage/single_faculty.html
{% extends 'base_layout.html' %}

{% block content %}

<h3> Faculty ID Number: {{faculty.faculty_id}} </h3>

<p> First Name: {{faculty.faculty_name_first}}  </p>
<p> Last Name: {{faculty.faculty_name_last}}  </p>
<p> Email: {{faculty.faculty_email}}  </p>

{% endblock %}

capstone/LandingPage/templates/LandingPage/single_student.html
{% extends 'base_layout.html' %}

{% block content %}

<h3> Student ID Number: {{student.student_id}} </h3>

<p> First Name: {{student.student_name_first}}  </p>
<p> Last Name: {{student.student_name_last}}  </p>
<p> Email: {{student.student_email}}  </p>

{% endblock %}

capstone/LandingPage/templates/LandingPage/student_list.html
{% extends 'base_layout.html' %}

{% block content %}

<h2> Student </h2>

<form method = "GET" action = "{% url 'LandingPage:all_students'%}">
    <input name="q" value = "{{request.GET.q}}" placeholder = "search..">
    <button class="btn btn-success" type="submit">
	    Search
	</button>
</form>

{% if student_list %}
<ul>
    {% for student in student_list %}
    <li>
        <a href="{% url 'LandingPage:single_student' student.student_id %}">{{ student.student_name_last }}</a>
    </li>
    {% endfor %}
</ul>
{% else %}
<p>
    No Student Available
</p>
{% endif %}
{% endblock %}