capstone/capstone/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('courses/', include('coursesDB.urls', namespace = 'courses')),
    path('opath/', include("opath.urls")),
    url(r'^accounts/', include('accounts.urls')),
  	path('LandingPage/', include('LandingPage.urls')),
    path('course_search/', include('course_search.urls', namespace = 'course_search')),
    path('profile', include('user_profile.urls')),
  	path('', include('LandingPage.urls')),
]

capstone/coursesDB/urls.py
from django.urls import path

from . import views

app_name = 'courses'
urlpatterns = [
    path('', views.index, name='index'),
    path('all', views.get_courses, name='all_courses'),
    path('<course_id>', views.CourseSingleView, name='single_course'),
]

capstone/opath/urls.py
from django.urls import path
from . import views
from django.contrib import admin


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name = 'opath'),
]

capstone/coursesDB/models.py
from django.db import models

# Create your models here.


class Courses(models.Model):
    course_json = models.TextField()
    course_number = models.TextField()

    def __unicode__(self):
        return self.course_number

capstone/coursesDB/views.py
from django.shortcuts import get_object_or_404, render
from django.views import generic
from django.db.models import Q
from django.contrib.auth.decorators import login_required
import json

# Create your views here.
from .models import Courses

@login_required(login_url="/accounts/login/")
def index(request):
    course = Courses.objects.get(course_number="MGT500")
    course_dictionary = json.loads(course.course_json)
    return render(request, 'coursesDB/single_course.html', {'course': course_dictionary})

@login_required(login_url="/accounts/login/")
def get_courses(request, ):
    lst_of_courses = []
    query = request.GET.get('q')
    if query:
        try:
            courses_objects = Courses.objects.filter(course_number__contains = query)
            for course_object in courses_objects:
                course_dictionary = json.loads(course_object.course_json)
                lst_of_courses.append(course_dictionary)
        except:
            lst_of_courses = []
    else:
        courses_objects = Courses.objects.all()
        for course_object in courses_objects:
            course_dictionary = json.loads(course_object.course_json)
            lst_of_courses.append(course_dictionary)
    return render(request, 'coursesDB/all.html', {'lst_of_courses': lst_of_courses})

@login_required(login_url="/accounts/login/")
def CourseSingleView(request, course_id):
    try:
        course = Courses.objects.get(course_number=course_id)
    except:
	    return render(request, 'coursesDB/missing_course.html')
    course_dictionary = json.loads(course.course_json)
    return render(request, 'coursesDB/single_course.html', {'course': course_dictionary})

capstone/coursesDB/templates/coursesDB/all.html
{% extends 'base_layout.html' %}

{% block content %}

<h2> Available Courses </h2>

<form method = "GET" action = "{% url 'courses:all_courses'%}">
    <input name="q" value = "{{request.GET.q}}" placeholder = "search..">
    <button class="btn btn-success" type="submit">
	    Search
	</button>
</form>

{% for course_dictionary in lst_of_courses %}

<hr>
<h3><a href="{% url 'courses:single_course' course_dictionary.course_number %}">{{ course_dictionary.course_number }}: {{course_dictionary.course_name}}</a></h3>

<p> Course Description: {{course_dictionary.course_description}}  </p>
<p> Course Offered: {{course_dictionary.quarters_offered}}  </p>

<br>

{% endfor %}
{% endblock %}

capstone/coursesDB/templates/coursesDB/missing_course.html
{% extends 'base_layout.html' %}

{% block content %}

This course does not exist.

{% endblock %}

capstone/coursesDB/templates/coursesDB/single_course.html
{% extends 'base_layout.html' %}

{% block content %}

<h3>{{course.course_number}}: {{course.course_name}} </h3>

<p> Course Description: {{course.course_description}}  </p>
<p> Course Offered: {{course.quarters_offered}}  </p>
<p> Offered Online: {{course.offered_online}}  </p>
<p> Prerequisites: {{course.prereqs}}  </p>

{% endblock %}